### ISSUE TITLE
Check out transaction sign size.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-protob#2]
Check the transaction [signature size](https://github.com/simelo/hardware-wallet-protob/blob/0ef99566e6892bd1115ca5fad19abdf0c8db2458/protob/messages.options#L31), the signed transaction will be check with a [different size](https://github.com/simelo/hardware-wallet-protob/blob/0ef99566e6892bd1115ca5fad19abdf0c8db2458/protob/messages.options#L27). This look like an inconsitence(bug).

**Comment by olemis** [comment]
@stdevAlDen this repository contains the common protobuffer definitions to be used by all other projects . Check if the version in this one is correct , if not change it .

**Comment by stdevAlDen** [comment]
@olemis currently solve

https://github.com/skycoin/hardware-wallet-protob/blob/c3266da30b9de27ddc2e08f762a386bb2dd5a5d6/protob/messages/messages.options#L29

https://github.com/skycoin/hardware-wallet-protob/blob/c3266da30b9de27ddc2e08f762a386bb2dd5a5d6/protob/messages/messages.options#L24
