### ISSUE TITLE
Problem when signing a transaction with 8 inputs

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-protob#31]
## Expected Behavior
When a transaction with 8 inputs is signed, 8 valid signatures should be received.

## Actual Behavior
When a transaction with 8 inputs is signed, the last signature is invalid, it has `\u0000` at the end. Also, when trying to sign a transaction with 8 inputs using the JS library it shows `Wire format is invalid { ProtocolError: missing required 'padding'` before the signaturas list. The last signature looks like this: `f411060b48442990ce09e50ad9485ca682e1936e0dff8910443eb59ca1297a6e7391e6ace3b3706ff21e49b571c90691b2f910849215bb6d6e5f5b6303102fbd0\u0000`

## Steps to Reproduce the Problem
I tested usign the JS library. I called the `devSkycoinTransactionSign` function with 8 inputs. It does not matter if the inputs are the same or not.

## Specifications

  - Version: Recent develop hardware wallet firmware and JS library.
  - Platform: Windows
  - Subsystem: X64

**Comment by Senyoret1** [comment]
Apparently this problem is only present in the JS library, so opened the issue again in https://github.com/skycoin/hardware-wallet-js/issues/102

**Comment by olemis** [comment]
> Apparently this problem is only present in the JS library

ok , let's keep this one in case changes needed in protobuffer specs
