### ISSUE TITLE
Add .npmignore

### ISSUE THREAD

**Issue by stdevStark** [skycoin/hardware-wallet-protob#51]
**Is your feature request related to a problem? Please describe.**
`js/skycoin.js` not added in packages.

**Describe the solution you'd like**
Add `.npmignore`

**Describe alternatives you've considered**
Add files one by one is difficult and can be wrong if `.proto` files change.

**Additional context**
[`npm` ignore rules](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) are : 

> if there's no `.npmignore` file, but there is a `.gitignore` file, then `npm` will ignore the stuff matched by the `.gitignore` file.

Files in `./js/` are ignored by `git`.

Related to skycoin/hardware-wallet-js#112

**Comment by olemis** [comment]
I do not understand very well what this is for .

**Comment by stdevStark** [comment]
The file `js/skycoin.js` is not included in release because git ignores all files in `js/` . `npm` uses `.gitignore` if there is not `.npmignore` .

**Comment by stdevStark** [comment]
if you add `.npmignore` and not exclude `js/` the file is added.
